---
    name: CI
    
    on: push
    
    jobs:
      static_analysis:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
    
          - name: python setup
            uses: actions/setup-python@v2
            with:
              python-version: '3.11.7'
    
          - name: dependencies installation
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
    
          - name: pylint check
            run: pylint *.py

          - name: mypy check
            run: mypy --strict .

          - name: sqlfluff check
            run: sqlfluff lint --dialect duckdb sql/*.sql